version: "3"

services:
  pdf-field-parser:
    restart: always
    build: .
    networks:
      - ${TRAEFIK_NETWORK:-web}
    env_file:
      - .env
    labels:
      traefik.docker.network: ${TRAEFIK_NETWORK:-web}
      traefik.http.routers.pdf-field-parser.rule: Host(`${SITE_URL:-pdf-field-parser.example.test}`)
      traefik.http.routers.pdf-field-parser.tls: ${TLS:-true}
      traefik.http.routers.pdf-field-parser.tls.certresolver: ${CERTRESOLVER:-letsencrypt}

networks:
  web:
    external: true